### ISSUE TITLE
Should EnumerableExhibit#to_json accept args?

### ISSUE THREAD

**Issue by tomdmaguire** [objects-on-rails/display-case#53]
I have run into an issue when trying to use an instance of EnumerableExhibit along with rails controller respond_to method.

When the rails renderer calls to_json on the given object, it does so with arguments. This causes a 1 for 0 arguments errors when providing an EnumerableExhibit.

A proposed solution would be to allow args to be passed to EnumerableExhibit:

```ruby
class DisplayCase::EnumerableExhibit
  # ...
  def to_json(*args)
    as_json(*args).to_json(*args)
  end
end
```

Do you have any thoughts on this?

**Comment by codeodor** [comment]
Yes, it should. Please send a pull request. :smile:
