### ISSUE TITLE
Error with Namespaced Class reloading

### ISSUE THREAD

**Issue by pdobb** [objects-on-rails/display-case#60]
I'm seeing a new error now:

![image](https://cloud.githubusercontent.com/assets/64674/17488913/87f3128c-5d69-11e6-99b8-1b38f4b40de7.png)

I haven't had time to dig in so just reporting this now. My initial question was just: why split on `::` then select all elements of the array and try to constantize. What were you trying to accomplish here?

When I do get this error, the result is that the object doesn't get reloaded.

I don't know if it's weird but... it seems like it's almost a timing thing when I get this. Like if I change my exhibit and then refresh the page right away I see it. Whereas if I wait a few seconds then I don't see it.

**Comment by codeodor** [comment]
I think it should be `[0..-2]` not to -1. The goal is to remove the constant and reload it so it can pick up changes, because it was reloading them, but having the old copy around was messing things up.

**Comment by pdobb** [comment]
Would you like a pull request for the change? I can make it and try it out locally for a while and then you could merge when it feels good.

**Comment by pdobb** [comment]
Issue is fixed by PR #61.
